spring:
  application:
    name: transporte-pagos
  datasource:
    url: jdbc:mysql://localhost:3306/msrv_pagos
    username: micro_pagos
    password: transporte_pago_msrv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0